### ISSUE TITLE
Unable to render the .gltf file in IOS but worked in android

### ISSUE THREAD

**Issue by Hpaneru** [CariusLars/ar_flutter_plugin#128]
Hi! I have tried  multiple types of .gltf files to render. Some of them rendered but some of them are not render and doesn't shows any error!

The animation files from this link https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0 were successfully rendered, but i am trying to render other than the files from this url they are not rendered!

I download the animation file from the above link and load from the local file by trying to render in  type: NodeType.localGLTF2.

The error is like below:- 
![Screen Shot 2022-08-01 at 20 25 04](https://user-images.githubusercontent.com/39861156/182174979-12106834-bf5d-47a4-9a44-ea829468496d.png)

The file which I want to render is;- 
[Test_Animations.zip](https://github.com/CariusLars/ar_flutter_plugin/files/9234787/Test_Animations.zip)

I don't find and difference between my file and the animation files from the above github link!

P.S I am using node type as:-  type: NodeType.localGLTF2,

@CariusLars Could you plz look into it!

**Comment by SebastianAT** [comment]
I also faced a similar issue when loading files from the web directly from github. In order to solve i had to add "?raw=true" to the end of the github link like this: 
https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/Duck/glTF-Binary/Duck.glb?raw=true

But you try to load it from your local space so have you confirmed that the actual model is there? added to pubspec? For me this works.
