### ISSUE TITLE
AR ios/android functionalities 

### ISSUE THREAD

**Issue by rubenteste** [CariusLars/ar_flutter_plugin#4]
> Reality composer

Hi @rubenteste,
thanks for your PR. A quick note before I comment on Reality Composer: Your PR does not add any code, so I'd suggest moving this conversation to an [Issue](https://github.com/CariusLars/ar_flutter_plugin/issues).

Reality Composer is great app for creating scenes and models, but it's not a feature of an iOS AR app, rather a means to create and export the models then used by the app. I agree that importing a `.rcproject` file is very convenient, however, it is highly specific to iOS. The Flutter AR Plugin aims to provide cross-platform functionality, so adding a feature that works under iOS only makes no sense. For this reason, I decided to go with .GLTF and .GLB models first to offer a common format. The plugin currently uses Sceneform to handle 3D models for ARCore, which can deal with model formats like `.obj`, `.glTF`, and `.fbx`. If you find a way to appropriately convert scenes and models from Reality Composer to be used with Sceneform and ARCore as well, feel free to implement it and create a PR, that would be a great feature! Exporting to `USDZ` format first could be a starting point worth looking into.

Best regards,

Lars

_Originally posted by @CariusLars in https://github.com/CariusLars/ar_flutter_plugin/issues/3#issuecomment-800138650_

Ok, it makes sense, I thought that reality composer could be implemented for android and not just iOS.
Are you thinking of implementing some anchor functionality in an image to place an object? as well as after that to be able to rotate the object and zoom in on the object?
Thanks.

**Comment by CariusLars** [comment]
thanks for moving this to an issue! :+1: 
Yes anchors are definitely going to be an essential part of this plugin, as a matter of fact I'm currently implementing plane anchors to which objects can be attached, should be done soon. 
The image anchors you are mentioning will also be included, however, that's a bit further down the road because cloud anchor functionality is currently my first priority and there's still a lot to do in that direction. Both the [arkit_flutter_plugin](https://github.com/olexale/arkit_flutter_plugin) and the [arcore_flutter_plugin](https://github.com/giandifra/arcore_flutter_plugin) support image anchors, so including them into this project is just a matter of creating a common interface and slightly adapting the existing implementations. If you find the time, it could be a good starting point for a contribution, if not, you'll probably have to wait for a bit longer until I get around to doing it :smile: 
Cheers,
Lars

**Comment by CariusLars** [comment]
> thanks for moving this to an issue! 👍
> Yes anchors are definitely going to be an essential part of this plugin, as a matter of fact I'm currently implementing plane anchors to which objects can be attached, should be done soon.
> The image anchors you are mentioning will also be included, however, that's a bit further down the road because cloud anchor functionality is currently my first priority and there's still a lot to do in that direction. Both the [arkit_flutter_plugin](https://github.com/olexale/arkit_flutter_plugin) and the [arcore_flutter_plugin](https://github.com/giandifra/arcore_flutter_plugin) support image anchors, so including them into this project is just a matter of creating a common interface and slightly adapting the existing implementations. If you find the time, it could be a good starting point for a contribution, if not, you'll probably have to wait for a bit longer until I get around to doing it 😄
> Cheers,
> Lars

Short addition to this: I'll make the anchor class extensible so contributers can add additional types of anchors such as image anchors, so in case you want to contribute it will probably make sense to wait until this is published, I'll get it done by the end of the week so you have a starting point to work with :)
