### ISSUE TITLE
Object anchor/tracking

### ISSUE THREAD

**Issue by aleonnet** [CariusLars/ar_flutter_plugin#6]
Hi @CariusLars
Amazing plugin you're creating, congrats. 
I'm new to AR. I was just wondering how can I use your work to add this kind of feature(https://www.youtube.com/watch?v=-wgf6Zvn6rg) to an App. Will it be possible?

Thanks.
Alessandro

**Comment by CariusLars** [comment]
Hi @aleonnet,
thanks for your message! Cool application in the video. In the current state of the plugin, this isn't possible because it relies on a feature called "image anchors" which I haven't implemented yet. However, adding image anchors to the plugin is on the roadmap so hopefully it will be possible to anchor AR-overlays on barcodes as shown in the video soon! 
I've already implemented the plugin in a way that enables users to dynamically load 3D-models from the internet during runtime, so once I (or another contributor) adds image anchors (and possibly a barcode-reader feature which shouldn't be difficult) it should be fairly straightforward to  query the individual router connection data from a server and then display it in AR :)
Cheers,
Lars

**Comment by aleonnet** [comment]
> Hi @aleonnet,
> thanks for your message! Cool application in the video. In the current state of the plugin, this isn't possible because it relies on a feature called "image anchors" which I haven't implemented yet. However, adding image anchors to the plugin is on the roadmap so hopefully it will be possible to anchor AR-overlays on barcodes as shown in the video soon!
> I've already implemented the plugin in a way that enables users to dynamically load 3D-models from the internet during runtime, so once I (or another contributor) adds image anchors (and possibly a barcode-reader feature which shouldn't be difficult) it should be fairly straightforward to query the individual router connection data from a server and then display it in AR :)
> Cheers,
> Lars

Thank you! I'll look forward to use your work on my app. Keep it up the good job!

**Comment by FatihBaycu** [comment]
> > Hi @aleonnet,
> > thanks for your message! Cool application in the video. In the current state of the plugin, this isn't possible because it relies on a feature called "image anchors" which I haven't implemented yet. However, adding image anchors to the plugin is on the roadmap so hopefully it will be possible to anchor AR-overlays on barcodes as shown in the video soon!
> > I've already implemented the plugin in a way that enables users to dynamically load 3D-models from the internet during runtime, so once I (or another contributor) adds image anchors (and possibly a barcode-reader feature which shouldn't be difficult) it should be fairly straightforward to query the individual router connection data from a server and then display it in AR :)
> > Cheers,
> > Lars
> 
> Thank you! I'll look forward to use your work on my app. Keep it up the good job!

Have you checked if this feature is available in new commits? Thanks.
